### ISSUE TITLE
Make the create hackathon page responsive

### ISSUE THREAD

**Issue by thisShouldNotBeWorking** [con-artist/Hackathon-app#1]
Once you run the app in the development mode navigate to http://localhost:3000/create. Try viewing in mobile view you will notice that the page is shifting if you click and drag.  The problem lies in the Scss file . You need to fix this issue and make the page properly responsive

**Comment by MarkWasfy00** [comment]
can i work on this ?

**Comment by thisShouldNotBeWorking** [comment]
sure

**Comment by MarkWasfy00** [comment]
iam sorry but the code is kinda a mess , in the mean while  reassign me again if you want me to refactor your code from 0 but i need the figma file or the design sketch

**Comment by thisShouldNotBeWorking** [comment]
If you can refactor the code go ahead. That would be  much appreciated.
Here are the figma links :

https://www.figma.com/file/g6elhXaMArmnIFgUjiKhT6/Hackathon?node-id=0%3A1

Prototype:

https://www.figma.com/proto/g6elhXaMArmnIFgUjiKhT6/Hackathon?page-id=0%3A1&node-id=9%3A163&viewport=-223%2C146%2C0.12&scaling=min-zoom&starting-point-node-id=9%3A163
